// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserProfileSetNickname.proto

package net.iGap.proto;

public final class ProtoUserProfileNickname {
  private ProtoUserProfileNickname() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface UserProfileSetNicknameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.UserProfileSetNickname)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    net.iGap.proto.ProtoRequest.Request getRequest();

    /**
     * <code>optional string nickname = 2;</code>
     */
    java.lang.String getNickname();
    /**
     * <code>optional string nickname = 2;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();
  }
  /**
   * Protobuf type {@code proto.UserProfileSetNickname}
   */
  public  static final class UserProfileSetNickname extends
      com.google.protobuf.GeneratedMessageLite<
          UserProfileSetNickname, UserProfileSetNickname.Builder> implements
      // @@protoc_insertion_point(message_implements:proto.UserProfileSetNickname)
      UserProfileSetNicknameOrBuilder {
    private UserProfileSetNickname() {
      nickname_ = "";
    }
    public static final int REQUEST_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoRequest.Request request_;
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public net.iGap.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    private void setRequest(net.iGap.proto.ProtoRequest.Request value) {
      if (value == null) {
        throw new NullPointerException();
      }
      request_ = value;
      
      }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    private void setRequest(
        net.iGap.proto.ProtoRequest.Request.Builder builderForValue) {
      request_ = builderForValue.build();
      
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    private void mergeRequest(net.iGap.proto.ProtoRequest.Request value) {
      if (request_ != null &&
          request_ != net.iGap.proto.ProtoRequest.Request.getDefaultInstance()) {
        request_ =
          net.iGap.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
      } else {
        request_ = value;
      }
      
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    private void clearRequest() {  request_ = null;
      
    }

    public static final int NICKNAME_FIELD_NUMBER = 2;
    private java.lang.String nickname_;
    /**
     * <code>optional string nickname = 2;</code>
     */
    public java.lang.String getNickname() {
      return nickname_;
    }
    /**
     * <code>optional string nickname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(nickname_);
    }
    /**
     * <code>optional string nickname = 2;</code>
     */
    private void setNickname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nickname_ = value;
    }
    /**
     * <code>optional string nickname = 2;</code>
     */
    private void clearNickname() {
      
      nickname_ = getDefaultInstance().getNickname();
    }
    /**
     * <code>optional string nickname = 2;</code>
     */
    private void setNicknameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nickname_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (!nickname_.isEmpty()) {
        output.writeString(2, getNickname());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (!nickname_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getNickname());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code proto.UserProfileSetNickname}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname, Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.UserProfileSetNickname)
        net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameOrBuilder {
      // Construct using net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public boolean hasRequest() {
        return instance.hasRequest();
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.Request getRequest() {
        return instance.getRequest();
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(net.iGap.proto.ProtoRequest.Request value) {
        copyOnWrite();
        instance.setRequest(value);
        return this;
        }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(
          net.iGap.proto.ProtoRequest.Request.Builder builderForValue) {
        copyOnWrite();
        instance.setRequest(builderForValue);
        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder mergeRequest(net.iGap.proto.ProtoRequest.Request value) {
        copyOnWrite();
        instance.mergeRequest(value);
        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder clearRequest() {  copyOnWrite();
        instance.clearRequest();
        return this;
      }

      /**
       * <code>optional string nickname = 2;</code>
       */
      public java.lang.String getNickname() {
        return instance.getNickname();
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        return instance.getNicknameBytes();
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public Builder setNickname(
          java.lang.String value) {
        copyOnWrite();
        instance.setNickname(value);
        return this;
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public Builder clearNickname() {
        copyOnWrite();
        instance.clearNickname();
        return this;
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNicknameBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.UserProfileSetNickname)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname other = (net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname) arg1;
          request_ = visitor.visitMessage(request_, other.request_);
          nickname_ = visitor.visitString(!nickname_.isEmpty(), nickname_,
              !other.nickname_.isEmpty(), other.nickname_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  net.iGap.proto.ProtoRequest.Request.Builder subBuilder = null;
                  if (request_ != null) {
                    subBuilder = request_.toBuilder();
                  }
                  request_ = input.readMessage(net.iGap.proto.ProtoRequest.Request.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(request_);
                    request_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  nickname_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:proto.UserProfileSetNickname)
    private static final net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserProfileSetNickname();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNickname getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserProfileSetNickname> PARSER;

    public static com.google.protobuf.Parser<UserProfileSetNickname> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UserProfileSetNicknameResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.UserProfileSetNicknameResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    net.iGap.proto.ProtoResponse.Response getResponse();

    /**
     * <code>optional string nickname = 2;</code>
     */
    java.lang.String getNickname();
    /**
     * <code>optional string nickname = 2;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <code>optional string initials = 3;</code>
     */
    java.lang.String getInitials();
    /**
     * <code>optional string initials = 3;</code>
     */
    com.google.protobuf.ByteString
        getInitialsBytes();
  }
  /**
   * Protobuf type {@code proto.UserProfileSetNicknameResponse}
   */
  public  static final class UserProfileSetNicknameResponse extends
      com.google.protobuf.GeneratedMessageLite<
          UserProfileSetNicknameResponse, UserProfileSetNicknameResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:proto.UserProfileSetNicknameResponse)
      UserProfileSetNicknameResponseOrBuilder {
    private UserProfileSetNicknameResponse() {
      nickname_ = "";
      initials_ = "";
    }
    public static final int RESPONSE_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoResponse.Response response_;
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public net.iGap.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    private void setResponse(net.iGap.proto.ProtoResponse.Response value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      
      }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    private void setResponse(
        net.iGap.proto.ProtoResponse.Response.Builder builderForValue) {
      response_ = builderForValue.build();
      
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    private void mergeResponse(net.iGap.proto.ProtoResponse.Response value) {
      if (response_ != null &&
          response_ != net.iGap.proto.ProtoResponse.Response.getDefaultInstance()) {
        response_ =
          net.iGap.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    private void clearResponse() {  response_ = null;
      
    }

    public static final int NICKNAME_FIELD_NUMBER = 2;
    private java.lang.String nickname_;
    /**
     * <code>optional string nickname = 2;</code>
     */
    public java.lang.String getNickname() {
      return nickname_;
    }
    /**
     * <code>optional string nickname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(nickname_);
    }
    /**
     * <code>optional string nickname = 2;</code>
     */
    private void setNickname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nickname_ = value;
    }
    /**
     * <code>optional string nickname = 2;</code>
     */
    private void clearNickname() {
      
      nickname_ = getDefaultInstance().getNickname();
    }
    /**
     * <code>optional string nickname = 2;</code>
     */
    private void setNicknameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nickname_ = value.toStringUtf8();
    }

    public static final int INITIALS_FIELD_NUMBER = 3;
    private java.lang.String initials_;
    /**
     * <code>optional string initials = 3;</code>
     */
    public java.lang.String getInitials() {
      return initials_;
    }
    /**
     * <code>optional string initials = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInitialsBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(initials_);
    }
    /**
     * <code>optional string initials = 3;</code>
     */
    private void setInitials(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      initials_ = value;
    }
    /**
     * <code>optional string initials = 3;</code>
     */
    private void clearInitials() {
      
      initials_ = getDefaultInstance().getInitials();
    }
    /**
     * <code>optional string initials = 3;</code>
     */
    private void setInitialsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      initials_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      if (!nickname_.isEmpty()) {
        output.writeString(2, getNickname());
      }
      if (!initials_.isEmpty()) {
        output.writeString(3, getInitials());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      if (!nickname_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getNickname());
      }
      if (!initials_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getInitials());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code proto.UserProfileSetNicknameResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.UserProfileSetNicknameResponse)
        net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponseOrBuilder {
      // Construct using net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public boolean hasResponse() {
        return instance.hasResponse();
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.Response getResponse() {
        return instance.getResponse();
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(net.iGap.proto.ProtoResponse.Response value) {
        copyOnWrite();
        instance.setResponse(value);
        return this;
        }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(
          net.iGap.proto.ProtoResponse.Response.Builder builderForValue) {
        copyOnWrite();
        instance.setResponse(builderForValue);
        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder mergeResponse(net.iGap.proto.ProtoResponse.Response value) {
        copyOnWrite();
        instance.mergeResponse(value);
        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder clearResponse() {  copyOnWrite();
        instance.clearResponse();
        return this;
      }

      /**
       * <code>optional string nickname = 2;</code>
       */
      public java.lang.String getNickname() {
        return instance.getNickname();
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        return instance.getNicknameBytes();
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public Builder setNickname(
          java.lang.String value) {
        copyOnWrite();
        instance.setNickname(value);
        return this;
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public Builder clearNickname() {
        copyOnWrite();
        instance.clearNickname();
        return this;
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNicknameBytes(value);
        return this;
      }

      /**
       * <code>optional string initials = 3;</code>
       */
      public java.lang.String getInitials() {
        return instance.getInitials();
      }
      /**
       * <code>optional string initials = 3;</code>
       */
      public com.google.protobuf.ByteString
          getInitialsBytes() {
        return instance.getInitialsBytes();
      }
      /**
       * <code>optional string initials = 3;</code>
       */
      public Builder setInitials(
          java.lang.String value) {
        copyOnWrite();
        instance.setInitials(value);
        return this;
      }
      /**
       * <code>optional string initials = 3;</code>
       */
      public Builder clearInitials() {
        copyOnWrite();
        instance.clearInitials();
        return this;
      }
      /**
       * <code>optional string initials = 3;</code>
       */
      public Builder setInitialsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setInitialsBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.UserProfileSetNicknameResponse)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse other = (net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse) arg1;
          response_ = visitor.visitMessage(response_, other.response_);
          nickname_ = visitor.visitString(!nickname_.isEmpty(), nickname_,
              !other.nickname_.isEmpty(), other.nickname_);
          initials_ = visitor.visitString(!initials_.isEmpty(), initials_,
              !other.initials_.isEmpty(), other.initials_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  net.iGap.proto.ProtoResponse.Response.Builder subBuilder = null;
                  if (response_ != null) {
                    subBuilder = response_.toBuilder();
                  }
                  response_ = input.readMessage(net.iGap.proto.ProtoResponse.Response.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(response_);
                    response_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  nickname_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  initials_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:proto.UserProfileSetNicknameResponse)
    private static final net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserProfileSetNicknameResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static net.iGap.proto.ProtoUserProfileNickname.UserProfileSetNicknameResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserProfileSetNicknameResponse> PARSER;

    public static com.google.protobuf.Parser<UserProfileSetNicknameResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
