// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserSessionGetActiveList.proto

package net.iGap.proto;

public final class ProtoUserSessionGetActiveList {
  private ProtoUserSessionGetActiveList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface UserSessionGetActiveListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.UserSessionGetActiveList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    net.iGap.proto.ProtoRequest.Request getRequest();
  }
  /**
   * Protobuf type {@code proto.UserSessionGetActiveList}
   */
  public  static final class UserSessionGetActiveList extends
      com.google.protobuf.GeneratedMessageLite<
          UserSessionGetActiveList, UserSessionGetActiveList.Builder> implements
      // @@protoc_insertion_point(message_implements:proto.UserSessionGetActiveList)
      UserSessionGetActiveListOrBuilder {
    private UserSessionGetActiveList() {
    }
    public static final int REQUEST_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoRequest.Request request_;
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public net.iGap.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    private void setRequest(net.iGap.proto.ProtoRequest.Request value) {
      if (value == null) {
        throw new NullPointerException();
      }
      request_ = value;
      
      }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    private void setRequest(
        net.iGap.proto.ProtoRequest.Request.Builder builderForValue) {
      request_ = builderForValue.build();
      
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    private void mergeRequest(net.iGap.proto.ProtoRequest.Request value) {
      if (request_ != null &&
          request_ != net.iGap.proto.ProtoRequest.Request.getDefaultInstance()) {
        request_ =
          net.iGap.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
      } else {
        request_ = value;
      }
      
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    private void clearRequest() {  request_ = null;
      
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code proto.UserSessionGetActiveList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList, Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.UserSessionGetActiveList)
        net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListOrBuilder {
      // Construct using net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public boolean hasRequest() {
        return instance.hasRequest();
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.Request getRequest() {
        return instance.getRequest();
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(net.iGap.proto.ProtoRequest.Request value) {
        copyOnWrite();
        instance.setRequest(value);
        return this;
        }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(
          net.iGap.proto.ProtoRequest.Request.Builder builderForValue) {
        copyOnWrite();
        instance.setRequest(builderForValue);
        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder mergeRequest(net.iGap.proto.ProtoRequest.Request value) {
        copyOnWrite();
        instance.mergeRequest(value);
        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder clearRequest() {  copyOnWrite();
        instance.clearRequest();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.UserSessionGetActiveList)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList other = (net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList) arg1;
          request_ = visitor.visitMessage(request_, other.request_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  net.iGap.proto.ProtoRequest.Request.Builder subBuilder = null;
                  if (request_ != null) {
                    subBuilder = request_.toBuilder();
                  }
                  request_ = input.readMessage(net.iGap.proto.ProtoRequest.Request.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(request_);
                    request_ = subBuilder.buildPartial();
                  }

                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:proto.UserSessionGetActiveList)
    private static final net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserSessionGetActiveList();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserSessionGetActiveList> PARSER;

    public static com.google.protobuf.Parser<UserSessionGetActiveList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UserSessionGetActiveListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.UserSessionGetActiveListResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    net.iGap.proto.ProtoResponse.Response getResponse();

    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    java.util.List<net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session> 
        getSessionList();
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session getSession(int index);
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    int getSessionCount();
  }
  /**
   * Protobuf type {@code proto.UserSessionGetActiveListResponse}
   */
  public  static final class UserSessionGetActiveListResponse extends
      com.google.protobuf.GeneratedMessageLite<
          UserSessionGetActiveListResponse, UserSessionGetActiveListResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:proto.UserSessionGetActiveListResponse)
      UserSessionGetActiveListResponseOrBuilder {
    private UserSessionGetActiveListResponse() {
      session_ = emptyProtobufList();
    }
    public interface SessionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:proto.UserSessionGetActiveListResponse.Session)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>optional uint64 session_id = 1;</code>
       */
      long getSessionId();

      /**
       * <code>optional string app_name = 2;</code>
       */
      java.lang.String getAppName();
      /**
       * <code>optional string app_name = 2;</code>
       */
      com.google.protobuf.ByteString
          getAppNameBytes();

      /**
       * <code>optional uint32 app_id = 3;</code>
       */
      int getAppId();

      /**
       * <code>optional uint32 app_build_version = 4;</code>
       */
      int getAppBuildVersion();

      /**
       * <code>optional string app_version = 5;</code>
       */
      java.lang.String getAppVersion();
      /**
       * <code>optional string app_version = 5;</code>
       */
      com.google.protobuf.ByteString
          getAppVersionBytes();

      /**
       * <code>optional .proto.Platform platform = 6;</code>
       */
      int getPlatformValue();
      /**
       * <code>optional .proto.Platform platform = 6;</code>
       */
      net.iGap.proto.ProtoGlobal.Platform getPlatform();

      /**
       * <code>optional string platform_version = 7;</code>
       */
      java.lang.String getPlatformVersion();
      /**
       * <code>optional string platform_version = 7;</code>
       */
      com.google.protobuf.ByteString
          getPlatformVersionBytes();

      /**
       * <code>optional .proto.Device device = 8;</code>
       */
      int getDeviceValue();
      /**
       * <code>optional .proto.Device device = 8;</code>
       */
      net.iGap.proto.ProtoGlobal.Device getDevice();

      /**
       * <code>optional string device_name = 9;</code>
       */
      java.lang.String getDeviceName();
      /**
       * <code>optional string device_name = 9;</code>
       */
      com.google.protobuf.ByteString
          getDeviceNameBytes();

      /**
       * <code>optional .proto.Language language = 10;</code>
       */
      int getLanguageValue();
      /**
       * <code>optional .proto.Language language = 10;</code>
       */
      net.iGap.proto.ProtoGlobal.Language getLanguage();

      /**
       * <code>optional string country = 11;</code>
       */
      java.lang.String getCountry();
      /**
       * <code>optional string country = 11;</code>
       */
      com.google.protobuf.ByteString
          getCountryBytes();

      /**
       * <code>optional bool current = 12;</code>
       */
      boolean getCurrent();

      /**
       * <code>optional uint32 create_time = 13;</code>
       */
      int getCreateTime();

      /**
       * <code>optional uint32 active_time = 14;</code>
       */
      int getActiveTime();

      /**
       * <code>optional string ip = 15;</code>
       */
      java.lang.String getIp();
      /**
       * <code>optional string ip = 15;</code>
       */
      com.google.protobuf.ByteString
          getIpBytes();
    }
    /**
     * Protobuf type {@code proto.UserSessionGetActiveListResponse.Session}
     */
    public  static final class Session extends
        com.google.protobuf.GeneratedMessageLite<
            Session, Session.Builder> implements
        // @@protoc_insertion_point(message_implements:proto.UserSessionGetActiveListResponse.Session)
        SessionOrBuilder {
      private Session() {
        appName_ = "";
        appVersion_ = "";
        platformVersion_ = "";
        deviceName_ = "";
        country_ = "";
        ip_ = "";
      }
      public static final int SESSION_ID_FIELD_NUMBER = 1;
      private long sessionId_;
      /**
       * <code>optional uint64 session_id = 1;</code>
       */
      public long getSessionId() {
        return sessionId_;
      }
      /**
       * <code>optional uint64 session_id = 1;</code>
       */
      private void setSessionId(long value) {
        
        sessionId_ = value;
      }
      /**
       * <code>optional uint64 session_id = 1;</code>
       */
      private void clearSessionId() {
        
        sessionId_ = 0L;
      }

      public static final int APP_NAME_FIELD_NUMBER = 2;
      private java.lang.String appName_;
      /**
       * <code>optional string app_name = 2;</code>
       */
      public java.lang.String getAppName() {
        return appName_;
      }
      /**
       * <code>optional string app_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(appName_);
      }
      /**
       * <code>optional string app_name = 2;</code>
       */
      private void setAppName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appName_ = value;
      }
      /**
       * <code>optional string app_name = 2;</code>
       */
      private void clearAppName() {
        
        appName_ = getDefaultInstance().getAppName();
      }
      /**
       * <code>optional string app_name = 2;</code>
       */
      private void setAppNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appName_ = value.toStringUtf8();
      }

      public static final int APP_ID_FIELD_NUMBER = 3;
      private int appId_;
      /**
       * <code>optional uint32 app_id = 3;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <code>optional uint32 app_id = 3;</code>
       */
      private void setAppId(int value) {
        
        appId_ = value;
      }
      /**
       * <code>optional uint32 app_id = 3;</code>
       */
      private void clearAppId() {
        
        appId_ = 0;
      }

      public static final int APP_BUILD_VERSION_FIELD_NUMBER = 4;
      private int appBuildVersion_;
      /**
       * <code>optional uint32 app_build_version = 4;</code>
       */
      public int getAppBuildVersion() {
        return appBuildVersion_;
      }
      /**
       * <code>optional uint32 app_build_version = 4;</code>
       */
      private void setAppBuildVersion(int value) {
        
        appBuildVersion_ = value;
      }
      /**
       * <code>optional uint32 app_build_version = 4;</code>
       */
      private void clearAppBuildVersion() {
        
        appBuildVersion_ = 0;
      }

      public static final int APP_VERSION_FIELD_NUMBER = 5;
      private java.lang.String appVersion_;
      /**
       * <code>optional string app_version = 5;</code>
       */
      public java.lang.String getAppVersion() {
        return appVersion_;
      }
      /**
       * <code>optional string app_version = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAppVersionBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(appVersion_);
      }
      /**
       * <code>optional string app_version = 5;</code>
       */
      private void setAppVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appVersion_ = value;
      }
      /**
       * <code>optional string app_version = 5;</code>
       */
      private void clearAppVersion() {
        
        appVersion_ = getDefaultInstance().getAppVersion();
      }
      /**
       * <code>optional string app_version = 5;</code>
       */
      private void setAppVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appVersion_ = value.toStringUtf8();
      }

      public static final int PLATFORM_FIELD_NUMBER = 6;
      private int platform_;
      /**
       * <code>optional .proto.Platform platform = 6;</code>
       */
      public int getPlatformValue() {
        return platform_;
      }
      /**
       * <code>optional .proto.Platform platform = 6;</code>
       */
      public net.iGap.proto.ProtoGlobal.Platform getPlatform() {
        net.iGap.proto.ProtoGlobal.Platform result = net.iGap.proto.ProtoGlobal.Platform.forNumber(platform_);
        return result == null ? net.iGap.proto.ProtoGlobal.Platform.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .proto.Platform platform = 6;</code>
       */
      private void setPlatformValue(int value) {
          platform_ = value;
      }
      /**
       * <code>optional .proto.Platform platform = 6;</code>
       */
      private void setPlatform(net.iGap.proto.ProtoGlobal.Platform value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        platform_ = value.getNumber();
      }
      /**
       * <code>optional .proto.Platform platform = 6;</code>
       */
      private void clearPlatform() {
        
        platform_ = 0;
      }

      public static final int PLATFORM_VERSION_FIELD_NUMBER = 7;
      private java.lang.String platformVersion_;
      /**
       * <code>optional string platform_version = 7;</code>
       */
      public java.lang.String getPlatformVersion() {
        return platformVersion_;
      }
      /**
       * <code>optional string platform_version = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformVersionBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(platformVersion_);
      }
      /**
       * <code>optional string platform_version = 7;</code>
       */
      private void setPlatformVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        platformVersion_ = value;
      }
      /**
       * <code>optional string platform_version = 7;</code>
       */
      private void clearPlatformVersion() {
        
        platformVersion_ = getDefaultInstance().getPlatformVersion();
      }
      /**
       * <code>optional string platform_version = 7;</code>
       */
      private void setPlatformVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        platformVersion_ = value.toStringUtf8();
      }

      public static final int DEVICE_FIELD_NUMBER = 8;
      private int device_;
      /**
       * <code>optional .proto.Device device = 8;</code>
       */
      public int getDeviceValue() {
        return device_;
      }
      /**
       * <code>optional .proto.Device device = 8;</code>
       */
      public net.iGap.proto.ProtoGlobal.Device getDevice() {
        net.iGap.proto.ProtoGlobal.Device result = net.iGap.proto.ProtoGlobal.Device.forNumber(device_);
        return result == null ? net.iGap.proto.ProtoGlobal.Device.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .proto.Device device = 8;</code>
       */
      private void setDeviceValue(int value) {
          device_ = value;
      }
      /**
       * <code>optional .proto.Device device = 8;</code>
       */
      private void setDevice(net.iGap.proto.ProtoGlobal.Device value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        device_ = value.getNumber();
      }
      /**
       * <code>optional .proto.Device device = 8;</code>
       */
      private void clearDevice() {
        
        device_ = 0;
      }

      public static final int DEVICE_NAME_FIELD_NUMBER = 9;
      private java.lang.String deviceName_;
      /**
       * <code>optional string device_name = 9;</code>
       */
      public java.lang.String getDeviceName() {
        return deviceName_;
      }
      /**
       * <code>optional string device_name = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceNameBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(deviceName_);
      }
      /**
       * <code>optional string device_name = 9;</code>
       */
      private void setDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceName_ = value;
      }
      /**
       * <code>optional string device_name = 9;</code>
       */
      private void clearDeviceName() {
        
        deviceName_ = getDefaultInstance().getDeviceName();
      }
      /**
       * <code>optional string device_name = 9;</code>
       */
      private void setDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceName_ = value.toStringUtf8();
      }

      public static final int LANGUAGE_FIELD_NUMBER = 10;
      private int language_;
      /**
       * <code>optional .proto.Language language = 10;</code>
       */
      public int getLanguageValue() {
        return language_;
      }
      /**
       * <code>optional .proto.Language language = 10;</code>
       */
      public net.iGap.proto.ProtoGlobal.Language getLanguage() {
        net.iGap.proto.ProtoGlobal.Language result = net.iGap.proto.ProtoGlobal.Language.forNumber(language_);
        return result == null ? net.iGap.proto.ProtoGlobal.Language.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .proto.Language language = 10;</code>
       */
      private void setLanguageValue(int value) {
          language_ = value;
      }
      /**
       * <code>optional .proto.Language language = 10;</code>
       */
      private void setLanguage(net.iGap.proto.ProtoGlobal.Language value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        language_ = value.getNumber();
      }
      /**
       * <code>optional .proto.Language language = 10;</code>
       */
      private void clearLanguage() {
        
        language_ = 0;
      }

      public static final int COUNTRY_FIELD_NUMBER = 11;
      private java.lang.String country_;
      /**
       * <code>optional string country = 11;</code>
       */
      public java.lang.String getCountry() {
        return country_;
      }
      /**
       * <code>optional string country = 11;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(country_);
      }
      /**
       * <code>optional string country = 11;</code>
       */
      private void setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        country_ = value;
      }
      /**
       * <code>optional string country = 11;</code>
       */
      private void clearCountry() {
        
        country_ = getDefaultInstance().getCountry();
      }
      /**
       * <code>optional string country = 11;</code>
       */
      private void setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        country_ = value.toStringUtf8();
      }

      public static final int CURRENT_FIELD_NUMBER = 12;
      private boolean current_;
      /**
       * <code>optional bool current = 12;</code>
       */
      public boolean getCurrent() {
        return current_;
      }
      /**
       * <code>optional bool current = 12;</code>
       */
      private void setCurrent(boolean value) {
        
        current_ = value;
      }
      /**
       * <code>optional bool current = 12;</code>
       */
      private void clearCurrent() {
        
        current_ = false;
      }

      public static final int CREATE_TIME_FIELD_NUMBER = 13;
      private int createTime_;
      /**
       * <code>optional uint32 create_time = 13;</code>
       */
      public int getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional uint32 create_time = 13;</code>
       */
      private void setCreateTime(int value) {
        
        createTime_ = value;
      }
      /**
       * <code>optional uint32 create_time = 13;</code>
       */
      private void clearCreateTime() {
        
        createTime_ = 0;
      }

      public static final int ACTIVE_TIME_FIELD_NUMBER = 14;
      private int activeTime_;
      /**
       * <code>optional uint32 active_time = 14;</code>
       */
      public int getActiveTime() {
        return activeTime_;
      }
      /**
       * <code>optional uint32 active_time = 14;</code>
       */
      private void setActiveTime(int value) {
        
        activeTime_ = value;
      }
      /**
       * <code>optional uint32 active_time = 14;</code>
       */
      private void clearActiveTime() {
        
        activeTime_ = 0;
      }

      public static final int IP_FIELD_NUMBER = 15;
      private java.lang.String ip_;
      /**
       * <code>optional string ip = 15;</code>
       */
      public java.lang.String getIp() {
        return ip_;
      }
      /**
       * <code>optional string ip = 15;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(ip_);
      }
      /**
       * <code>optional string ip = 15;</code>
       */
      private void setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
      }
      /**
       * <code>optional string ip = 15;</code>
       */
      private void clearIp() {
        
        ip_ = getDefaultInstance().getIp();
      }
      /**
       * <code>optional string ip = 15;</code>
       */
      private void setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value.toStringUtf8();
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (sessionId_ != 0L) {
          output.writeUInt64(1, sessionId_);
        }
        if (!appName_.isEmpty()) {
          output.writeString(2, getAppName());
        }
        if (appId_ != 0) {
          output.writeUInt32(3, appId_);
        }
        if (appBuildVersion_ != 0) {
          output.writeUInt32(4, appBuildVersion_);
        }
        if (!appVersion_.isEmpty()) {
          output.writeString(5, getAppVersion());
        }
        if (platform_ != net.iGap.proto.ProtoGlobal.Platform.UNKNOWN_PLATFORM.getNumber()) {
          output.writeEnum(6, platform_);
        }
        if (!platformVersion_.isEmpty()) {
          output.writeString(7, getPlatformVersion());
        }
        if (device_ != net.iGap.proto.ProtoGlobal.Device.UNKNOWN_DEVICE.getNumber()) {
          output.writeEnum(8, device_);
        }
        if (!deviceName_.isEmpty()) {
          output.writeString(9, getDeviceName());
        }
        if (language_ != net.iGap.proto.ProtoGlobal.Language.EN_US.getNumber()) {
          output.writeEnum(10, language_);
        }
        if (!country_.isEmpty()) {
          output.writeString(11, getCountry());
        }
        if (current_ != false) {
          output.writeBool(12, current_);
        }
        if (createTime_ != 0) {
          output.writeUInt32(13, createTime_);
        }
        if (activeTime_ != 0) {
          output.writeUInt32(14, activeTime_);
        }
        if (!ip_.isEmpty()) {
          output.writeString(15, getIp());
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (sessionId_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(1, sessionId_);
        }
        if (!appName_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getAppName());
        }
        if (appId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(3, appId_);
        }
        if (appBuildVersion_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(4, appBuildVersion_);
        }
        if (!appVersion_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(5, getAppVersion());
        }
        if (platform_ != net.iGap.proto.ProtoGlobal.Platform.UNKNOWN_PLATFORM.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(6, platform_);
        }
        if (!platformVersion_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(7, getPlatformVersion());
        }
        if (device_ != net.iGap.proto.ProtoGlobal.Device.UNKNOWN_DEVICE.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(8, device_);
        }
        if (!deviceName_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(9, getDeviceName());
        }
        if (language_ != net.iGap.proto.ProtoGlobal.Language.EN_US.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(10, language_);
        }
        if (!country_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(11, getCountry());
        }
        if (current_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(12, current_);
        }
        if (createTime_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(13, createTime_);
        }
        if (activeTime_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(14, activeTime_);
        }
        if (!ip_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(15, getIp());
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code proto.UserSessionGetActiveListResponse.Session}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session, Builder> implements
          // @@protoc_insertion_point(builder_implements:proto.UserSessionGetActiveListResponse.Session)
          net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.SessionOrBuilder {
        // Construct using net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional uint64 session_id = 1;</code>
         */
        public long getSessionId() {
          return instance.getSessionId();
        }
        /**
         * <code>optional uint64 session_id = 1;</code>
         */
        public Builder setSessionId(long value) {
          copyOnWrite();
          instance.setSessionId(value);
          return this;
        }
        /**
         * <code>optional uint64 session_id = 1;</code>
         */
        public Builder clearSessionId() {
          copyOnWrite();
          instance.clearSessionId();
          return this;
        }

        /**
         * <code>optional string app_name = 2;</code>
         */
        public java.lang.String getAppName() {
          return instance.getAppName();
        }
        /**
         * <code>optional string app_name = 2;</code>
         */
        public com.google.protobuf.ByteString
            getAppNameBytes() {
          return instance.getAppNameBytes();
        }
        /**
         * <code>optional string app_name = 2;</code>
         */
        public Builder setAppName(
            java.lang.String value) {
          copyOnWrite();
          instance.setAppName(value);
          return this;
        }
        /**
         * <code>optional string app_name = 2;</code>
         */
        public Builder clearAppName() {
          copyOnWrite();
          instance.clearAppName();
          return this;
        }
        /**
         * <code>optional string app_name = 2;</code>
         */
        public Builder setAppNameBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setAppNameBytes(value);
          return this;
        }

        /**
         * <code>optional uint32 app_id = 3;</code>
         */
        public int getAppId() {
          return instance.getAppId();
        }
        /**
         * <code>optional uint32 app_id = 3;</code>
         */
        public Builder setAppId(int value) {
          copyOnWrite();
          instance.setAppId(value);
          return this;
        }
        /**
         * <code>optional uint32 app_id = 3;</code>
         */
        public Builder clearAppId() {
          copyOnWrite();
          instance.clearAppId();
          return this;
        }

        /**
         * <code>optional uint32 app_build_version = 4;</code>
         */
        public int getAppBuildVersion() {
          return instance.getAppBuildVersion();
        }
        /**
         * <code>optional uint32 app_build_version = 4;</code>
         */
        public Builder setAppBuildVersion(int value) {
          copyOnWrite();
          instance.setAppBuildVersion(value);
          return this;
        }
        /**
         * <code>optional uint32 app_build_version = 4;</code>
         */
        public Builder clearAppBuildVersion() {
          copyOnWrite();
          instance.clearAppBuildVersion();
          return this;
        }

        /**
         * <code>optional string app_version = 5;</code>
         */
        public java.lang.String getAppVersion() {
          return instance.getAppVersion();
        }
        /**
         * <code>optional string app_version = 5;</code>
         */
        public com.google.protobuf.ByteString
            getAppVersionBytes() {
          return instance.getAppVersionBytes();
        }
        /**
         * <code>optional string app_version = 5;</code>
         */
        public Builder setAppVersion(
            java.lang.String value) {
          copyOnWrite();
          instance.setAppVersion(value);
          return this;
        }
        /**
         * <code>optional string app_version = 5;</code>
         */
        public Builder clearAppVersion() {
          copyOnWrite();
          instance.clearAppVersion();
          return this;
        }
        /**
         * <code>optional string app_version = 5;</code>
         */
        public Builder setAppVersionBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setAppVersionBytes(value);
          return this;
        }

        /**
         * <code>optional .proto.Platform platform = 6;</code>
         */
        public int getPlatformValue() {
          return instance.getPlatformValue();
        }
        /**
         * <code>optional .proto.Platform platform = 6;</code>
         */
        public Builder setPlatformValue(int value) {
          copyOnWrite();
          instance.setPlatformValue(value);
          return this;
        }
        /**
         * <code>optional .proto.Platform platform = 6;</code>
         */
        public net.iGap.proto.ProtoGlobal.Platform getPlatform() {
          return instance.getPlatform();
        }
        /**
         * <code>optional .proto.Platform platform = 6;</code>
         */
        public Builder setPlatform(net.iGap.proto.ProtoGlobal.Platform value) {
          copyOnWrite();
          instance.setPlatform(value);
          return this;
        }
        /**
         * <code>optional .proto.Platform platform = 6;</code>
         */
        public Builder clearPlatform() {
          copyOnWrite();
          instance.clearPlatform();
          return this;
        }

        /**
         * <code>optional string platform_version = 7;</code>
         */
        public java.lang.String getPlatformVersion() {
          return instance.getPlatformVersion();
        }
        /**
         * <code>optional string platform_version = 7;</code>
         */
        public com.google.protobuf.ByteString
            getPlatformVersionBytes() {
          return instance.getPlatformVersionBytes();
        }
        /**
         * <code>optional string platform_version = 7;</code>
         */
        public Builder setPlatformVersion(
            java.lang.String value) {
          copyOnWrite();
          instance.setPlatformVersion(value);
          return this;
        }
        /**
         * <code>optional string platform_version = 7;</code>
         */
        public Builder clearPlatformVersion() {
          copyOnWrite();
          instance.clearPlatformVersion();
          return this;
        }
        /**
         * <code>optional string platform_version = 7;</code>
         */
        public Builder setPlatformVersionBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setPlatformVersionBytes(value);
          return this;
        }

        /**
         * <code>optional .proto.Device device = 8;</code>
         */
        public int getDeviceValue() {
          return instance.getDeviceValue();
        }
        /**
         * <code>optional .proto.Device device = 8;</code>
         */
        public Builder setDeviceValue(int value) {
          copyOnWrite();
          instance.setDeviceValue(value);
          return this;
        }
        /**
         * <code>optional .proto.Device device = 8;</code>
         */
        public net.iGap.proto.ProtoGlobal.Device getDevice() {
          return instance.getDevice();
        }
        /**
         * <code>optional .proto.Device device = 8;</code>
         */
        public Builder setDevice(net.iGap.proto.ProtoGlobal.Device value) {
          copyOnWrite();
          instance.setDevice(value);
          return this;
        }
        /**
         * <code>optional .proto.Device device = 8;</code>
         */
        public Builder clearDevice() {
          copyOnWrite();
          instance.clearDevice();
          return this;
        }

        /**
         * <code>optional string device_name = 9;</code>
         */
        public java.lang.String getDeviceName() {
          return instance.getDeviceName();
        }
        /**
         * <code>optional string device_name = 9;</code>
         */
        public com.google.protobuf.ByteString
            getDeviceNameBytes() {
          return instance.getDeviceNameBytes();
        }
        /**
         * <code>optional string device_name = 9;</code>
         */
        public Builder setDeviceName(
            java.lang.String value) {
          copyOnWrite();
          instance.setDeviceName(value);
          return this;
        }
        /**
         * <code>optional string device_name = 9;</code>
         */
        public Builder clearDeviceName() {
          copyOnWrite();
          instance.clearDeviceName();
          return this;
        }
        /**
         * <code>optional string device_name = 9;</code>
         */
        public Builder setDeviceNameBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setDeviceNameBytes(value);
          return this;
        }

        /**
         * <code>optional .proto.Language language = 10;</code>
         */
        public int getLanguageValue() {
          return instance.getLanguageValue();
        }
        /**
         * <code>optional .proto.Language language = 10;</code>
         */
        public Builder setLanguageValue(int value) {
          copyOnWrite();
          instance.setLanguageValue(value);
          return this;
        }
        /**
         * <code>optional .proto.Language language = 10;</code>
         */
        public net.iGap.proto.ProtoGlobal.Language getLanguage() {
          return instance.getLanguage();
        }
        /**
         * <code>optional .proto.Language language = 10;</code>
         */
        public Builder setLanguage(net.iGap.proto.ProtoGlobal.Language value) {
          copyOnWrite();
          instance.setLanguage(value);
          return this;
        }
        /**
         * <code>optional .proto.Language language = 10;</code>
         */
        public Builder clearLanguage() {
          copyOnWrite();
          instance.clearLanguage();
          return this;
        }

        /**
         * <code>optional string country = 11;</code>
         */
        public java.lang.String getCountry() {
          return instance.getCountry();
        }
        /**
         * <code>optional string country = 11;</code>
         */
        public com.google.protobuf.ByteString
            getCountryBytes() {
          return instance.getCountryBytes();
        }
        /**
         * <code>optional string country = 11;</code>
         */
        public Builder setCountry(
            java.lang.String value) {
          copyOnWrite();
          instance.setCountry(value);
          return this;
        }
        /**
         * <code>optional string country = 11;</code>
         */
        public Builder clearCountry() {
          copyOnWrite();
          instance.clearCountry();
          return this;
        }
        /**
         * <code>optional string country = 11;</code>
         */
        public Builder setCountryBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setCountryBytes(value);
          return this;
        }

        /**
         * <code>optional bool current = 12;</code>
         */
        public boolean getCurrent() {
          return instance.getCurrent();
        }
        /**
         * <code>optional bool current = 12;</code>
         */
        public Builder setCurrent(boolean value) {
          copyOnWrite();
          instance.setCurrent(value);
          return this;
        }
        /**
         * <code>optional bool current = 12;</code>
         */
        public Builder clearCurrent() {
          copyOnWrite();
          instance.clearCurrent();
          return this;
        }

        /**
         * <code>optional uint32 create_time = 13;</code>
         */
        public int getCreateTime() {
          return instance.getCreateTime();
        }
        /**
         * <code>optional uint32 create_time = 13;</code>
         */
        public Builder setCreateTime(int value) {
          copyOnWrite();
          instance.setCreateTime(value);
          return this;
        }
        /**
         * <code>optional uint32 create_time = 13;</code>
         */
        public Builder clearCreateTime() {
          copyOnWrite();
          instance.clearCreateTime();
          return this;
        }

        /**
         * <code>optional uint32 active_time = 14;</code>
         */
        public int getActiveTime() {
          return instance.getActiveTime();
        }
        /**
         * <code>optional uint32 active_time = 14;</code>
         */
        public Builder setActiveTime(int value) {
          copyOnWrite();
          instance.setActiveTime(value);
          return this;
        }
        /**
         * <code>optional uint32 active_time = 14;</code>
         */
        public Builder clearActiveTime() {
          copyOnWrite();
          instance.clearActiveTime();
          return this;
        }

        /**
         * <code>optional string ip = 15;</code>
         */
        public java.lang.String getIp() {
          return instance.getIp();
        }
        /**
         * <code>optional string ip = 15;</code>
         */
        public com.google.protobuf.ByteString
            getIpBytes() {
          return instance.getIpBytes();
        }
        /**
         * <code>optional string ip = 15;</code>
         */
        public Builder setIp(
            java.lang.String value) {
          copyOnWrite();
          instance.setIp(value);
          return this;
        }
        /**
         * <code>optional string ip = 15;</code>
         */
        public Builder clearIp() {
          copyOnWrite();
          instance.clearIp();
          return this;
        }
        /**
         * <code>optional string ip = 15;</code>
         */
        public Builder setIpBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setIpBytes(value);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:proto.UserSessionGetActiveListResponse.Session)
      }
      protected final Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session other = (net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session) arg1;
            sessionId_ = visitor.visitLong(sessionId_ != 0L, sessionId_,
                other.sessionId_ != 0L, other.sessionId_);
            appName_ = visitor.visitString(!appName_.isEmpty(), appName_,
                !other.appName_.isEmpty(), other.appName_);
            appId_ = visitor.visitInt(appId_ != 0, appId_,
                other.appId_ != 0, other.appId_);
            appBuildVersion_ = visitor.visitInt(appBuildVersion_ != 0, appBuildVersion_,
                other.appBuildVersion_ != 0, other.appBuildVersion_);
            appVersion_ = visitor.visitString(!appVersion_.isEmpty(), appVersion_,
                !other.appVersion_.isEmpty(), other.appVersion_);
            platform_ = visitor.visitInt(platform_ != 0, platform_,    other.platform_ != 0, other.platform_);
            platformVersion_ = visitor.visitString(!platformVersion_.isEmpty(), platformVersion_,
                !other.platformVersion_.isEmpty(), other.platformVersion_);
            device_ = visitor.visitInt(device_ != 0, device_,    other.device_ != 0, other.device_);
            deviceName_ = visitor.visitString(!deviceName_.isEmpty(), deviceName_,
                !other.deviceName_.isEmpty(), other.deviceName_);
            language_ = visitor.visitInt(language_ != 0, language_,    other.language_ != 0, other.language_);
            country_ = visitor.visitString(!country_.isEmpty(), country_,
                !other.country_.isEmpty(), other.country_);
            current_ = visitor.visitBoolean(current_ != false, current_,
                other.current_ != false, other.current_);
            createTime_ = visitor.visitInt(createTime_ != 0, createTime_,
                other.createTime_ != 0, other.createTime_);
            activeTime_ = visitor.visitInt(activeTime_ != 0, activeTime_,
                other.activeTime_ != 0, other.activeTime_);
            ip_ = visitor.visitString(!ip_.isEmpty(), ip_,
                !other.ip_.isEmpty(), other.ip_);
            if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 8: {

                    sessionId_ = input.readUInt64();
                    break;
                  }
                  case 18: {
                    String s = input.readStringRequireUtf8();

                    appName_ = s;
                    break;
                  }
                  case 24: {

                    appId_ = input.readUInt32();
                    break;
                  }
                  case 32: {

                    appBuildVersion_ = input.readUInt32();
                    break;
                  }
                  case 42: {
                    String s = input.readStringRequireUtf8();

                    appVersion_ = s;
                    break;
                  }
                  case 48: {
                    int rawValue = input.readEnum();

                    platform_ = rawValue;
                    break;
                  }
                  case 58: {
                    String s = input.readStringRequireUtf8();

                    platformVersion_ = s;
                    break;
                  }
                  case 64: {
                    int rawValue = input.readEnum();

                    device_ = rawValue;
                    break;
                  }
                  case 74: {
                    String s = input.readStringRequireUtf8();

                    deviceName_ = s;
                    break;
                  }
                  case 80: {
                    int rawValue = input.readEnum();

                    language_ = rawValue;
                    break;
                  }
                  case 90: {
                    String s = input.readStringRequireUtf8();

                    country_ = s;
                    break;
                  }
                  case 96: {

                    current_ = input.readBool();
                    break;
                  }
                  case 104: {

                    createTime_ = input.readUInt32();
                    break;
                  }
                  case 112: {

                    activeTime_ = input.readUInt32();
                    break;
                  }
                  case 122: {
                    String s = input.readStringRequireUtf8();

                    ip_ = s;
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:proto.UserSessionGetActiveListResponse.Session)
      private static final net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Session();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Session> PARSER;

      public static com.google.protobuf.Parser<Session> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int RESPONSE_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoResponse.Response response_;
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public net.iGap.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    private void setResponse(net.iGap.proto.ProtoResponse.Response value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      
      }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    private void setResponse(
        net.iGap.proto.ProtoResponse.Response.Builder builderForValue) {
      response_ = builderForValue.build();
      
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    private void mergeResponse(net.iGap.proto.ProtoResponse.Response value) {
      if (response_ != null &&
          response_ != net.iGap.proto.ProtoResponse.Response.getDefaultInstance()) {
        response_ =
          net.iGap.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    private void clearResponse() {  response_ = null;
      
    }

    public static final int SESSION_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session> session_;
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    public java.util.List<net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session> getSessionList() {
      return session_;
    }
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    public java.util.List<? extends net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.SessionOrBuilder> 
        getSessionOrBuilderList() {
      return session_;
    }
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    public int getSessionCount() {
      return session_.size();
    }
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    public net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session getSession(int index) {
      return session_.get(index);
    }
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    public net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.SessionOrBuilder getSessionOrBuilder(
        int index) {
      return session_.get(index);
    }
    private void ensureSessionIsMutable() {
      if (!session_.isModifiable()) {
        session_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(session_);
       }
    }

    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    private void setSession(
        int index, net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureSessionIsMutable();
      session_.set(index, value);
    }
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    private void setSession(
        int index, net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session.Builder builderForValue) {
      ensureSessionIsMutable();
      session_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    private void addSession(net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureSessionIsMutable();
      session_.add(value);
    }
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    private void addSession(
        int index, net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureSessionIsMutable();
      session_.add(index, value);
    }
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    private void addSession(
        net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session.Builder builderForValue) {
      ensureSessionIsMutable();
      session_.add(builderForValue.build());
    }
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    private void addSession(
        int index, net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session.Builder builderForValue) {
      ensureSessionIsMutable();
      session_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    private void addAllSession(
        java.lang.Iterable<? extends net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session> values) {
      ensureSessionIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, session_);
    }
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    private void clearSession() {
      session_ = emptyProtobufList();
    }
    /**
     * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    private void removeSession(int index) {
      ensureSessionIsMutable();
      session_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      for (int i = 0; i < session_.size(); i++) {
        output.writeMessage(2, session_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      for (int i = 0; i < session_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, session_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code proto.UserSessionGetActiveListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.UserSessionGetActiveListResponse)
        net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponseOrBuilder {
      // Construct using net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public boolean hasResponse() {
        return instance.hasResponse();
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.Response getResponse() {
        return instance.getResponse();
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(net.iGap.proto.ProtoResponse.Response value) {
        copyOnWrite();
        instance.setResponse(value);
        return this;
        }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(
          net.iGap.proto.ProtoResponse.Response.Builder builderForValue) {
        copyOnWrite();
        instance.setResponse(builderForValue);
        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder mergeResponse(net.iGap.proto.ProtoResponse.Response value) {
        copyOnWrite();
        instance.mergeResponse(value);
        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder clearResponse() {  copyOnWrite();
        instance.clearResponse();
        return this;
      }

      /**
       * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
       */
      public java.util.List<net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session> getSessionList() {
        return java.util.Collections.unmodifiableList(
            instance.getSessionList());
      }
      /**
       * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
       */
      public int getSessionCount() {
        return instance.getSessionCount();
      }/**
       * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
       */
      public net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session getSession(int index) {
        return instance.getSession(index);
      }
      /**
       * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
       */
      public Builder setSession(
          int index, net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session value) {
        copyOnWrite();
        instance.setSession(index, value);
        return this;
      }
      /**
       * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
       */
      public Builder setSession(
          int index, net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session.Builder builderForValue) {
        copyOnWrite();
        instance.setSession(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
       */
      public Builder addSession(net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session value) {
        copyOnWrite();
        instance.addSession(value);
        return this;
      }
      /**
       * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
       */
      public Builder addSession(
          int index, net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session value) {
        copyOnWrite();
        instance.addSession(index, value);
        return this;
      }
      /**
       * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
       */
      public Builder addSession(
          net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session.Builder builderForValue) {
        copyOnWrite();
        instance.addSession(builderForValue);
        return this;
      }
      /**
       * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
       */
      public Builder addSession(
          int index, net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session.Builder builderForValue) {
        copyOnWrite();
        instance.addSession(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
       */
      public Builder addAllSession(
          java.lang.Iterable<? extends net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session> values) {
        copyOnWrite();
        instance.addAllSession(values);
        return this;
      }
      /**
       * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
       */
      public Builder clearSession() {
        copyOnWrite();
        instance.clearSession();
        return this;
      }
      /**
       * <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
       */
      public Builder removeSession(int index) {
        copyOnWrite();
        instance.removeSession(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.UserSessionGetActiveListResponse)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          session_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse other = (net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse) arg1;
          response_ = visitor.visitMessage(response_, other.response_);
          session_= visitor.visitList(session_, other.session_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  net.iGap.proto.ProtoResponse.Response.Builder subBuilder = null;
                  if (response_ != null) {
                    subBuilder = response_.toBuilder();
                  }
                  response_ = input.readMessage(net.iGap.proto.ProtoResponse.Response.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(response_);
                    response_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 18: {
                  if (!session_.isModifiable()) {
                    session_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(session_);
                  }
                  session_.add(
                      input.readMessage(net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.Session.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:proto.UserSessionGetActiveListResponse)
    private static final net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserSessionGetActiveListResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static net.iGap.proto.ProtoUserSessionGetActiveList.UserSessionGetActiveListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserSessionGetActiveListResponse> PARSER;

    public static com.google.protobuf.Parser<UserSessionGetActiveListResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
