// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserContactsStatus.proto

// Protobuf Java Version: 3.25.1
package net.iGap.proto;

public final class ProtoUserContactsStatus {
  private ProtoUserContactsStatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserContactsStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.UserContactsStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.proto.Request request = 1;</code>
     * @return The request.
     */
    net.iGap.proto.ProtoRequest.Request getRequest();
    /**
     * <code>.proto.Request request = 1;</code>
     */
    net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder();
  }
  /**
   * Protobuf type {@code proto.UserContactsStatus}
   */
  public static final class UserContactsStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.UserContactsStatus)
      UserContactsStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserContactsStatus.newBuilder() to construct.
    private UserContactsStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserContactsStatus() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserContactsStatus();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus.class, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus.Builder.class);
    }

    private int bitField0_;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoRequest.Request request_;
    /**
     * <code>.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    @java.lang.Override
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.Request request = 1;</code>
     * @return The request.
     */
    @java.lang.Override
    public net.iGap.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>.proto.Request request = 1;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getRequest());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus other = (net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus) obj;

      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.UserContactsStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.UserContactsStatus)
        net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus.class, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus.Builder.class);
      }

      // Construct using net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        request_ = null;
        if (requestBuilder_ != null) {
          requestBuilder_.dispose();
          requestBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatus_descriptor;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus getDefaultInstanceForType() {
        return net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus.getDefaultInstance();
      }

      @java.lang.Override
      public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus build() {
        net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus buildPartial() {
        net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus result = new net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.request_ = requestBuilder_ == null
              ? request_
              : requestBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus) {
          return mergeFrom((net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus other) {
        if (other == net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getRequestFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private net.iGap.proto.ProtoRequest.Request request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>.proto.Request request = 1;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.proto.Request request = 1;</code>
       * @return The request.
       */
      public net.iGap.proto.ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder setRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder setRequest(
          net.iGap.proto.ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder mergeRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            request_ != null &&
            request_ != net.iGap.proto.ProtoRequest.Request.getDefaultInstance()) {
            getRequestBuilder().mergeFrom(value);
          } else {
            request_ = value;
          }
        } else {
          requestBuilder_.mergeFrom(value);
        }
        if (request_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        bitField0_ = (bitField0_ & ~0x00000001);
        request_ = null;
        if (requestBuilder_ != null) {
          requestBuilder_.dispose();
          requestBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.Request.Builder getRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.UserContactsStatus)
    }

    // @@protoc_insertion_point(class_scope:proto.UserContactsStatus)
    private static final net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus();
    }

    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserContactsStatus>
        PARSER = new com.google.protobuf.AbstractParser<UserContactsStatus>() {
      @java.lang.Override
      public UserContactsStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserContactsStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserContactsStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserContactsStatusResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.UserContactsStatusResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.proto.Response response = 1;</code>
     * @return The response.
     */
    net.iGap.proto.ProtoResponse.Response getResponse();
    /**
     * <code>.proto.Response response = 1;</code>
     */
    net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
     */
    java.util.List<net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus> 
        getContactsStatusList();
    /**
     * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
     */
    net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus getContactsStatus(int index);
    /**
     * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
     */
    int getContactsStatusCount();
    /**
     * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
     */
    java.util.List<? extends net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatusOrBuilder> 
        getContactsStatusOrBuilderList();
    /**
     * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
     */
    net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatusOrBuilder getContactsStatusOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.UserContactsStatusResponse}
   */
  public static final class UserContactsStatusResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.UserContactsStatusResponse)
      UserContactsStatusResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserContactsStatusResponse.newBuilder() to construct.
    private UserContactsStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserContactsStatusResponse() {
      contactsStatus_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserContactsStatusResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.class, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.Builder.class);
    }

    public interface ContactStatusOrBuilder extends
        // @@protoc_insertion_point(interface_extends:proto.UserContactsStatusResponse.ContactStatus)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>uint64 user_id = 1;</code>
       * @return The userId.
       */
      long getUserId();

      /**
       * <code>uint32 last_seen = 2;</code>
       * @return The lastSeen.
       */
      int getLastSeen();

      /**
       * <code>.proto.UserContactsStatusResponse.ContactStatus.Status status = 3;</code>
       * @return The enum numeric value on the wire for status.
       */
      int getStatusValue();
      /**
       * <code>.proto.UserContactsStatusResponse.ContactStatus.Status status = 3;</code>
       * @return The status.
       */
      net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Status getStatus();
    }
    /**
     * Protobuf type {@code proto.UserContactsStatusResponse.ContactStatus}
     */
    public static final class ContactStatus extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:proto.UserContactsStatusResponse.ContactStatus)
        ContactStatusOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ContactStatus.newBuilder() to construct.
      private ContactStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ContactStatus() {
        status_ = 0;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new ContactStatus();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatusResponse_ContactStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatusResponse_ContactStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.class, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Builder.class);
      }

      /**
       * Protobuf enum {@code proto.UserContactsStatusResponse.ContactStatus.Status}
       */
      public enum Status
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>LONG_TIME_AGO = 0;</code>
         */
        LONG_TIME_AGO(0),
        /**
         * <code>LAST_MONTH = 1;</code>
         */
        LAST_MONTH(1),
        /**
         * <code>LAST_WEEK = 2;</code>
         */
        LAST_WEEK(2),
        /**
         * <code>ONLINE = 3;</code>
         */
        ONLINE(3),
        /**
         * <code>EXACTLY = 4;</code>
         */
        EXACTLY(4),
        /**
         * <code>RECENTLY = 5;</code>
         */
        RECENTLY(5),
        /**
         * <code>SUPPORT = 6;</code>
         */
        SUPPORT(6),
        /**
         * <code>SERVICE_NOTIFICATIONS = 7;</code>
         */
        SERVICE_NOTIFICATIONS(7),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>LONG_TIME_AGO = 0;</code>
         */
        public static final int LONG_TIME_AGO_VALUE = 0;
        /**
         * <code>LAST_MONTH = 1;</code>
         */
        public static final int LAST_MONTH_VALUE = 1;
        /**
         * <code>LAST_WEEK = 2;</code>
         */
        public static final int LAST_WEEK_VALUE = 2;
        /**
         * <code>ONLINE = 3;</code>
         */
        public static final int ONLINE_VALUE = 3;
        /**
         * <code>EXACTLY = 4;</code>
         */
        public static final int EXACTLY_VALUE = 4;
        /**
         * <code>RECENTLY = 5;</code>
         */
        public static final int RECENTLY_VALUE = 5;
        /**
         * <code>SUPPORT = 6;</code>
         */
        public static final int SUPPORT_VALUE = 6;
        /**
         * <code>SERVICE_NOTIFICATIONS = 7;</code>
         */
        public static final int SERVICE_NOTIFICATIONS_VALUE = 7;


        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static Status valueOf(int value) {
          return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static Status forNumber(int value) {
          switch (value) {
            case 0: return LONG_TIME_AGO;
            case 1: return LAST_MONTH;
            case 2: return LAST_WEEK;
            case 3: return ONLINE;
            case 4: return EXACTLY;
            case 5: return RECENTLY;
            case 6: return SUPPORT;
            case 7: return SERVICE_NOTIFICATIONS;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Status>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            Status> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<Status>() {
                public Status findValueByNumber(int number) {
                  return Status.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalStateException(
                "Can't get the descriptor of an unrecognized enum value.");
          }
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.getDescriptor().getEnumTypes().get(0);
        }

        private static final Status[] VALUES = values();

        public static Status valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private Status(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:proto.UserContactsStatusResponse.ContactStatus.Status)
      }

      public static final int USER_ID_FIELD_NUMBER = 1;
      private long userId_ = 0L;
      /**
       * <code>uint64 user_id = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }

      public static final int LAST_SEEN_FIELD_NUMBER = 2;
      private int lastSeen_ = 0;
      /**
       * <code>uint32 last_seen = 2;</code>
       * @return The lastSeen.
       */
      @java.lang.Override
      public int getLastSeen() {
        return lastSeen_;
      }

      public static final int STATUS_FIELD_NUMBER = 3;
      private int status_ = 0;
      /**
       * <code>.proto.UserContactsStatusResponse.ContactStatus.Status status = 3;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.proto.UserContactsStatusResponse.ContactStatus.Status status = 3;</code>
       * @return The status.
       */
      @java.lang.Override public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Status getStatus() {
        net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Status result = net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Status.forNumber(status_);
        return result == null ? net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Status.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (userId_ != 0L) {
          output.writeUInt64(1, userId_);
        }
        if (lastSeen_ != 0) {
          output.writeUInt32(2, lastSeen_);
        }
        if (status_ != net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Status.LONG_TIME_AGO.getNumber()) {
          output.writeEnum(3, status_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (userId_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(1, userId_);
        }
        if (lastSeen_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, lastSeen_);
        }
        if (status_ != net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Status.LONG_TIME_AGO.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(3, status_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus)) {
          return super.equals(obj);
        }
        net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus other = (net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus) obj;

        if (getUserId()
            != other.getUserId()) return false;
        if (getLastSeen()
            != other.getLastSeen()) return false;
        if (status_ != other.status_) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUserId());
        hash = (37 * hash) + LAST_SEEN_FIELD_NUMBER;
        hash = (53 * hash) + getLastSeen();
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_;
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code proto.UserContactsStatusResponse.ContactStatus}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:proto.UserContactsStatusResponse.ContactStatus)
          net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatusOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatusResponse_ContactStatus_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatusResponse_ContactStatus_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.class, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Builder.class);
        }

        // Construct using net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          userId_ = 0L;
          lastSeen_ = 0;
          status_ = 0;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatusResponse_ContactStatus_descriptor;
        }

        @java.lang.Override
        public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus getDefaultInstanceForType() {
          return net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.getDefaultInstance();
        }

        @java.lang.Override
        public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus build() {
          net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus buildPartial() {
          net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus result = new net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.userId_ = userId_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.lastSeen_ = lastSeen_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.status_ = status_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus) {
            return mergeFrom((net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus other) {
          if (other == net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.getDefaultInstance()) return this;
          if (other.getUserId() != 0L) {
            setUserId(other.getUserId());
          }
          if (other.getLastSeen() != 0) {
            setLastSeen(other.getLastSeen());
          }
          if (other.status_ != 0) {
            setStatusValue(other.getStatusValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  userId_ = input.readUInt64();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 8
                case 16: {
                  lastSeen_ = input.readUInt32();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 16
                case 24: {
                  status_ = input.readEnum();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 24
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private long userId_ ;
        /**
         * <code>uint64 user_id = 1;</code>
         * @return The userId.
         */
        @java.lang.Override
        public long getUserId() {
          return userId_;
        }
        /**
         * <code>uint64 user_id = 1;</code>
         * @param value The userId to set.
         * @return This builder for chaining.
         */
        public Builder setUserId(long value) {

          userId_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>uint64 user_id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearUserId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          userId_ = 0L;
          onChanged();
          return this;
        }

        private int lastSeen_ ;
        /**
         * <code>uint32 last_seen = 2;</code>
         * @return The lastSeen.
         */
        @java.lang.Override
        public int getLastSeen() {
          return lastSeen_;
        }
        /**
         * <code>uint32 last_seen = 2;</code>
         * @param value The lastSeen to set.
         * @return This builder for chaining.
         */
        public Builder setLastSeen(int value) {

          lastSeen_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 last_seen = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearLastSeen() {
          bitField0_ = (bitField0_ & ~0x00000002);
          lastSeen_ = 0;
          onChanged();
          return this;
        }

        private int status_ = 0;
        /**
         * <code>.proto.UserContactsStatusResponse.ContactStatus.Status status = 3;</code>
         * @return The enum numeric value on the wire for status.
         */
        @java.lang.Override public int getStatusValue() {
          return status_;
        }
        /**
         * <code>.proto.UserContactsStatusResponse.ContactStatus.Status status = 3;</code>
         * @param value The enum numeric value on the wire for status to set.
         * @return This builder for chaining.
         */
        public Builder setStatusValue(int value) {
          status_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>.proto.UserContactsStatusResponse.ContactStatus.Status status = 3;</code>
         * @return The status.
         */
        @java.lang.Override
        public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Status getStatus() {
          net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Status result = net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Status.forNumber(status_);
          return result == null ? net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Status.UNRECOGNIZED : result;
        }
        /**
         * <code>.proto.UserContactsStatusResponse.ContactStatus.Status status = 3;</code>
         * @param value The status to set.
         * @return This builder for chaining.
         */
        public Builder setStatus(net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Status value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000004;
          status_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.proto.UserContactsStatusResponse.ContactStatus.Status status = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearStatus() {
          bitField0_ = (bitField0_ & ~0x00000004);
          status_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:proto.UserContactsStatusResponse.ContactStatus)
      }

      // @@protoc_insertion_point(class_scope:proto.UserContactsStatusResponse.ContactStatus)
      private static final net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus();
      }

      public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ContactStatus>
          PARSER = new com.google.protobuf.AbstractParser<ContactStatus>() {
        @java.lang.Override
        public ContactStatus parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<ContactStatus> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ContactStatus> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int RESPONSE_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoResponse.Response response_;
    /**
     * <code>.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    @java.lang.Override
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.Response response = 1;</code>
     * @return The response.
     */
    @java.lang.Override
    public net.iGap.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>.proto.Response response = 1;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }

    public static final int CONTACTS_STATUS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus> contactsStatus_;
    /**
     * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
     */
    @java.lang.Override
    public java.util.List<net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus> getContactsStatusList() {
      return contactsStatus_;
    }
    /**
     * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatusOrBuilder> 
        getContactsStatusOrBuilderList() {
      return contactsStatus_;
    }
    /**
     * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
     */
    @java.lang.Override
    public int getContactsStatusCount() {
      return contactsStatus_.size();
    }
    /**
     * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus getContactsStatus(int index) {
      return contactsStatus_.get(index);
    }
    /**
     * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatusOrBuilder getContactsStatusOrBuilder(
        int index) {
      return contactsStatus_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getResponse());
      }
      for (int i = 0; i < contactsStatus_.size(); i++) {
        output.writeMessage(3, contactsStatus_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      for (int i = 0; i < contactsStatus_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, contactsStatus_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse other = (net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse) obj;

      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (!getContactsStatusList()
          .equals(other.getContactsStatusList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      if (getContactsStatusCount() > 0) {
        hash = (37 * hash) + CONTACTS_STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getContactsStatusList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.UserContactsStatusResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.UserContactsStatusResponse)
        net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatusResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatusResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.class, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.Builder.class);
      }

      // Construct using net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResponseFieldBuilder();
          getContactsStatusFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        response_ = null;
        if (responseBuilder_ != null) {
          responseBuilder_.dispose();
          responseBuilder_ = null;
        }
        if (contactsStatusBuilder_ == null) {
          contactsStatus_ = java.util.Collections.emptyList();
        } else {
          contactsStatus_ = null;
          contactsStatusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoUserContactsStatus.internal_static_proto_UserContactsStatusResponse_descriptor;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse getDefaultInstanceForType() {
        return net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.getDefaultInstance();
      }

      @java.lang.Override
      public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse build() {
        net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse buildPartial() {
        net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse result = new net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse result) {
        if (contactsStatusBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            contactsStatus_ = java.util.Collections.unmodifiableList(contactsStatus_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.contactsStatus_ = contactsStatus_;
        } else {
          result.contactsStatus_ = contactsStatusBuilder_.build();
        }
      }

      private void buildPartial0(net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.response_ = responseBuilder_ == null
              ? response_
              : responseBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse) {
          return mergeFrom((net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse other) {
        if (other == net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (contactsStatusBuilder_ == null) {
          if (!other.contactsStatus_.isEmpty()) {
            if (contactsStatus_.isEmpty()) {
              contactsStatus_ = other.contactsStatus_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureContactsStatusIsMutable();
              contactsStatus_.addAll(other.contactsStatus_);
            }
            onChanged();
          }
        } else {
          if (!other.contactsStatus_.isEmpty()) {
            if (contactsStatusBuilder_.isEmpty()) {
              contactsStatusBuilder_.dispose();
              contactsStatusBuilder_ = null;
              contactsStatus_ = other.contactsStatus_;
              bitField0_ = (bitField0_ & ~0x00000002);
              contactsStatusBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getContactsStatusFieldBuilder() : null;
            } else {
              contactsStatusBuilder_.addAllMessages(other.contactsStatus_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getResponseFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 26: {
                net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus m =
                    input.readMessage(
                        net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.parser(),
                        extensionRegistry);
                if (contactsStatusBuilder_ == null) {
                  ensureContactsStatusIsMutable();
                  contactsStatus_.add(m);
                } else {
                  contactsStatusBuilder_.addMessage(m);
                }
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private net.iGap.proto.ProtoResponse.Response response_;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>.proto.Response response = 1;</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.proto.Response response = 1;</code>
       * @return The response.
       */
      public net.iGap.proto.ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder setResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
        } else {
          responseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder setResponse(
          net.iGap.proto.ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder mergeResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            response_ != null &&
            response_ != net.iGap.proto.ProtoResponse.Response.getDefaultInstance()) {
            getResponseBuilder().mergeFrom(value);
          } else {
            response_ = value;
          }
        } else {
          responseBuilder_.mergeFrom(value);
        }
        if (response_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000001);
        response_ = null;
        if (responseBuilder_ != null) {
          responseBuilder_.dispose();
          responseBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.Response.Builder getResponseBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private java.util.List<net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus> contactsStatus_ =
        java.util.Collections.emptyList();
      private void ensureContactsStatusIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          contactsStatus_ = new java.util.ArrayList<net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus>(contactsStatus_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Builder, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatusOrBuilder> contactsStatusBuilder_;

      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public java.util.List<net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus> getContactsStatusList() {
        if (contactsStatusBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contactsStatus_);
        } else {
          return contactsStatusBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public int getContactsStatusCount() {
        if (contactsStatusBuilder_ == null) {
          return contactsStatus_.size();
        } else {
          return contactsStatusBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus getContactsStatus(int index) {
        if (contactsStatusBuilder_ == null) {
          return contactsStatus_.get(index);
        } else {
          return contactsStatusBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public Builder setContactsStatus(
          int index, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus value) {
        if (contactsStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsStatusIsMutable();
          contactsStatus_.set(index, value);
          onChanged();
        } else {
          contactsStatusBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public Builder setContactsStatus(
          int index, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Builder builderForValue) {
        if (contactsStatusBuilder_ == null) {
          ensureContactsStatusIsMutable();
          contactsStatus_.set(index, builderForValue.build());
          onChanged();
        } else {
          contactsStatusBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public Builder addContactsStatus(net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus value) {
        if (contactsStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsStatusIsMutable();
          contactsStatus_.add(value);
          onChanged();
        } else {
          contactsStatusBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public Builder addContactsStatus(
          int index, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus value) {
        if (contactsStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsStatusIsMutable();
          contactsStatus_.add(index, value);
          onChanged();
        } else {
          contactsStatusBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public Builder addContactsStatus(
          net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Builder builderForValue) {
        if (contactsStatusBuilder_ == null) {
          ensureContactsStatusIsMutable();
          contactsStatus_.add(builderForValue.build());
          onChanged();
        } else {
          contactsStatusBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public Builder addContactsStatus(
          int index, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Builder builderForValue) {
        if (contactsStatusBuilder_ == null) {
          ensureContactsStatusIsMutable();
          contactsStatus_.add(index, builderForValue.build());
          onChanged();
        } else {
          contactsStatusBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public Builder addAllContactsStatus(
          java.lang.Iterable<? extends net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus> values) {
        if (contactsStatusBuilder_ == null) {
          ensureContactsStatusIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contactsStatus_);
          onChanged();
        } else {
          contactsStatusBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public Builder clearContactsStatus() {
        if (contactsStatusBuilder_ == null) {
          contactsStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          contactsStatusBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public Builder removeContactsStatus(int index) {
        if (contactsStatusBuilder_ == null) {
          ensureContactsStatusIsMutable();
          contactsStatus_.remove(index);
          onChanged();
        } else {
          contactsStatusBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Builder getContactsStatusBuilder(
          int index) {
        return getContactsStatusFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatusOrBuilder getContactsStatusOrBuilder(
          int index) {
        if (contactsStatusBuilder_ == null) {
          return contactsStatus_.get(index);  } else {
          return contactsStatusBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public java.util.List<? extends net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatusOrBuilder> 
           getContactsStatusOrBuilderList() {
        if (contactsStatusBuilder_ != null) {
          return contactsStatusBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contactsStatus_);
        }
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Builder addContactsStatusBuilder() {
        return getContactsStatusFieldBuilder().addBuilder(
            net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Builder addContactsStatusBuilder(
          int index) {
        return getContactsStatusFieldBuilder().addBuilder(
            index, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.UserContactsStatusResponse.ContactStatus contacts_status = 3;</code>
       */
      public java.util.List<net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Builder> 
           getContactsStatusBuilderList() {
        return getContactsStatusFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Builder, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatusOrBuilder> 
          getContactsStatusFieldBuilder() {
        if (contactsStatusBuilder_ == null) {
          contactsStatusBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatus.Builder, net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse.ContactStatusOrBuilder>(
                  contactsStatus_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          contactsStatus_ = null;
        }
        return contactsStatusBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.UserContactsStatusResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.UserContactsStatusResponse)
    private static final net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse();
    }

    public static net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserContactsStatusResponse>
        PARSER = new com.google.protobuf.AbstractParser<UserContactsStatusResponse>() {
      @java.lang.Override
      public UserContactsStatusResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserContactsStatusResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserContactsStatusResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.iGap.proto.ProtoUserContactsStatus.UserContactsStatusResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserContactsStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UserContactsStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserContactsStatusResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UserContactsStatusResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserContactsStatusResponse_ContactStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UserContactsStatusResponse_ContactStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030UserContactsStatus.proto\022\005proto\032\rReque" +
      "st.proto\032\016Response.proto\"5\n\022UserContacts" +
      "Status\022\037\n\007request\030\001 \001(\0132\016.proto.Request\"" +
      "\223\003\n\032UserContactsStatusResponse\022!\n\010respon" +
      "se\030\001 \001(\0132\017.proto.Response\022H\n\017contacts_st" +
      "atus\030\003 \003(\0132/.proto.UserContactsStatusRes" +
      "ponse.ContactStatus\032\207\002\n\rContactStatus\022\017\n" +
      "\007user_id\030\001 \001(\004\022\021\n\tlast_seen\030\002 \001(\r\022F\n\006sta" +
      "tus\030\003 \001(\01626.proto.UserContactsStatusResp" +
      "onse.ContactStatus.Status\"\211\001\n\006Status\022\021\n\r" +
      "LONG_TIME_AGO\020\000\022\016\n\nLAST_MONTH\020\001\022\r\n\tLAST_" +
      "WEEK\020\002\022\n\n\006ONLINE\020\003\022\013\n\007EXACTLY\020\004\022\014\n\010RECEN" +
      "TLY\020\005\022\013\n\007SUPPORT\020\006\022\031\n\025SERVICE_NOTIFICATI" +
      "ONS\020\007B)\n\016net.iGap.protoB\027ProtoUserContac" +
      "tsStatusb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.iGap.proto.ProtoRequest.getDescriptor(),
          net.iGap.proto.ProtoResponse.getDescriptor(),
        });
    internal_static_proto_UserContactsStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_UserContactsStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UserContactsStatus_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_proto_UserContactsStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_UserContactsStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UserContactsStatusResponse_descriptor,
        new java.lang.String[] { "Response", "ContactsStatus", });
    internal_static_proto_UserContactsStatusResponse_ContactStatus_descriptor =
      internal_static_proto_UserContactsStatusResponse_descriptor.getNestedTypes().get(0);
    internal_static_proto_UserContactsStatusResponse_ContactStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UserContactsStatusResponse_ContactStatus_descriptor,
        new java.lang.String[] { "UserId", "LastSeen", "Status", });
    net.iGap.proto.ProtoRequest.getDescriptor();
    net.iGap.proto.ProtoResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
